# Generated by Django 5.0.6 on 2024-11-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0004_profile_created_at_profile_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='premium_ends',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='tenant', max_length=20),
        ),
    ]
